/****** Object:  Table [NBA].[TBL_PlayerGameTeamStats_PerPlayerSeason_Percent]    Script Date: 7/1/2022 2:50:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NBA].[TBL_PlayerGameTeamStats_PerPlayerSeason_Percent](
	[Player ID] [int] NULL,
	[Player] [nvarchar](201) NOT NULL,
	[Season] [smallint] NULL,
	[Team ID] [int] NULL,
	[Avg Points Per Minute] [float] NULL,
	[Avg Plus Minus Per Minute] [float] NULL,
	[Avg Field Goals Made per Minute] [float] NULL,
	[Avg Field Goals Attempted per Minute] [float] NULL,
	[Avg Free Throws Made per Minute] [float] NULL,
	[Avg Free Throws Attempted per Minute] [float] NULL,
	[Avg Three Pointers Made per Minute] [float] NULL,
	[Avg Three Pointers Attempted per Minute] [float] NULL,
	[Avg Offensive Rebounds per Minute] [float] NULL,
	[Avg Defensive Rebounds per Minute] [float] NULL,
	[Avg Total Rebounds per Minute] [float] NULL,
	[Avg Assists per Minute] [float] NULL,
	[Avg Personal Fouls per Minute] [float] NULL,
	[Avg Turnovers per Minute] [float] NULL,
	[Avg Blocks per Minute] [float] NULL,
	[Avg Points] [float] NULL,
	[Avg Plus Minus] [float] NULL,
	[Avg Field Goals Made] [float] NULL,
	[Avg Field Goals Attempted] [float] NULL,
	[Avg Field Goal %] [float] NULL,
	[Avg Free Throws Made] [float] NULL,
	[Avg Free Throws Attempted] [float] NULL,
	[Avg Free Throw %] [float] NULL,
	[Avg Three Pointers Made] [float] NULL,
	[Avg Three Pointers Attempted] [float] NULL,
	[Avg Three Pointer %] [float] NULL,
	[Avg Offensive Rebounds] [float] NULL,
	[Avg Defensive Rebounds] [float] NULL,
	[Avg Total Rebounds] [float] NULL,
	[Avg Assists] [float] NULL,
	[Avg Personal Fouls] [float] NULL,
	[Avg Turnovers] [float] NULL,
	[Avg Blocks] [float] NULL,
	[Time Played (Minutes)] [float] NULL,
	[Group] [varchar](7) NOT NULL,
	[Percent Points Per Minute] [float] NULL,
	[Percent Plus Minus Per Minute] [float] NULL,
	[Percent Field Goals Made Per Minute] [float] NULL,
	[Percent Field Goals Attempted Per Minute] [float] NULL,
	[Percent Free Throws Made Per Minute] [float] NULL,
	[Percent Free Throws Attempted Per Minute] [float] NULL,
	[Percent Three Pointers Made Per Minute] [float] NULL,
	[Percent Three Pointers Attempted Per Minute] [float] NULL,
	[Percent Offensive Rebounds Per Minute] [float] NULL,
	[Percent Defensive Rebounds Per Minute] [float] NULL,
	[Percent Total Rebounds Per Minute] [float] NULL,
	[Percent Assists Per Minute] [float] NULL,
	[Percent Personal Fouls Per Minute] [float] NULL,
	[Percent Turnovers Per Minute] [float] NULL,
	[Percent Blocks Per Minute] [float] NULL,
	[Percent Points Per Game] [float] NULL,
	[Percent Plus Minus Per Game] [float] NULL,
	[Percent Field Goals Made Per Game] [float] NULL,
	[Percent Field Goals Attempted Per Game] [float] NULL,
	[Percent Field Goal %] [float] NULL,
	[Percent Free Throws Made Per Game] [float] NULL,
	[Percent Free Throws Attempted Per Game] [float] NULL,
	[Percent Free Throw %] [float] NULL,
	[Percent Three Pointers Made Per Game] [float] NULL,
	[Percent Three Pointers Attempted Per Game] [float] NULL,
	[Percent Three Pointer %] [float] NULL,
	[Percent Offensive Rebounds Per Game] [float] NULL,
	[Percent Defensive Rebounds Per Game] [float] NULL,
	[Percent Total Rebounds Per Game] [float] NULL,
	[Percent Assists Per Game] [float] NULL,
	[Percent Personal Fouls Per Game] [float] NULL,
	[Percent Turnovers Per Game] [float] NULL,
	[Percent Blocks Per Game] [float] NULL
) ON [PRIMARY]
GO


